### ISSUE TITLE
card equalizer

### ISSUE THREAD

**Issue by claudioccm** [GovLab/open-government-research-exchange#111]

**Comment by tekd** [comment]
PR #123 affects the card equalizer fix and it is most noticeable on the cards with logos.

![screen shot 2016-05-02 at 10 13 00 am](https://cloud.githubusercontent.com/assets/9205941/14956674/f04982b6-104e-11e6-99c0-e52c5b94154b.png)

**Comment by claudioccm** [comment]
I can fix that. This is a css issue.
