### ISSUE TITLE
"false" - value is getting pulled in the subset jsons

### ISSUE THREAD

**Issue by claudioccm** [GovLab/open-government-research-exchange#13]

**Comment by mocxd** [comment]
can i just ignore `false` completely?

**Comment by claudioccm** [comment]
yes, you should ignore it. hehe

**Comment by mocxd** [comment]
are we dealing with this stuff on template level now, instead of on data level ?  / should i close this issue ?

**Comment by mocxd** [comment]
closing per discussion
