### ISSUE TITLE
error feedback for force refresh

### ISSUE THREAD

**Issue by claudioccm** [GovLab/open-government-research-exchange#139]

**Comment by mocxd** [comment]
i think this force refresh idea is the wrong approach. when i spoke to @juliachrusciel about this friday, i mentioned i had another, better idea, which is to simply replace the `html` back to the original state, and i even already gave the code for this in slack, super simple fix with jquery, and doesn't require clunky synchronous refresh

**Comment by claudioccm** [comment]
if it solves the problem and doesn't require 5 days of development, I'm fine with it.

**Comment by mocxd** [comment]
it is literally 2 lines of jquery ;)

**Comment by mocxd** [comment]
you just pull the innerhtml with `.html()` and save it to a variable, and then replace the html back with `.html(var)` when you hit the close button

in theory

**Comment by mocxd** [comment]
https://github.com/GovLab/open-government-research-exchange/pull/145 resolves
