### ISSUE TITLE
PhD, MD, MBA titles being pulled as Authors in the author subset

### ISSUE THREAD

**Issue by claudioccm** [GovLab/open-government-research-exchange#14]
![screen shot 2016-04-22 at 10 37 33 pm](https://cloud.githubusercontent.com/assets/1649373/14758854/e73e3fe8-08da-11e6-86ca-3ccbf16c4130.png)

**Comment by claudioccm** [comment]
let's do a new csv2json with new csv data, to make sure we have the very latest information. @annabialas confirmed that this information is not in the spreadsheet

**Comment by mocxd** [comment]
if the name is `John Doe, PhD.` the comma will parse it out as a new author.  whoever is editing the data should probably decide if they want to stop listing `Author 1, Author 2, Author 3`, etc in fields to show multiple authors, or if they want to clean up the incoming data to not have commas in an author's name.

alternatively a different delimiter could be used to separate authors, but is somewhat unintuitive maybe for those maintaining the data.  such as `;` or `&` or even a combination of characters like `--`
