### ISSUE TITLE
search results template snippet cut off

### ISSUE THREAD

**Issue by mocxd** [GovLab/open-government-research-exchange#149]
probably due to changes to the macro / template for the results

- 1
<img width="1280" alt="screen shot 2016-05-10 at 7 47 06 pm" src="https://cloud.githubusercontent.com/assets/1042629/15165951/0da0df54-16e8-11e6-9191-f84fdfe848a5.png">

- 2
<img width="1280" alt="screen shot 2016-05-10 at 7 48 35 pm" src="https://cloud.githubusercontent.com/assets/1042629/15165971/36e62b9e-16e8-11e6-82d4-345f145d5bc8.png">

**Comment by claudioccm** [comment]
yes. I changed the result macro

**Comment by mocxd** [comment]
this overlaps with https://github.com/GovLab/open-government-research-exchange/issues/154 , maybe we can discuss before i proceed
