### ISSUE TITLE
"un-slug" type values

### ISSUE THREAD

**Issue by claudioccm** [GovLab/open-government-research-exchange#17]

**Comment by tekd** [comment]
Does this need to be 'un-slugged' in the Google Doc?

**Comment by claudioccm** [comment]
honestly, I don't know how much work that would be. Let's leave it this way for now. It's not a big deal

**Comment by tekd** [comment]
This might actually be a gulp issue for @mocxd. Both organization and type values are being slugged upon mapping. 

` 'Organization'          : { value : 'organization', slugify : true },`
`  'Publication Type'      : { value : 'type', slugify : true },`
