### ISSUE TITLE
Organization filter titles

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-government-research-exchange#57]
Organization filter in category pages has hyphenated lower case titles (some repeat, for example see http://govlab.github.io/open-government-research-exchange/69ef6c90056666a97d39365918bbea9a-expert-networking.html)

**Comment by claudioccm** [comment]
this is due to data inconsistency. It will all get fixed with time. But we were focusing on the bigger stuff

**Comment by annabialas** [comment]
hm, in the organization column they're all good? i capitalized some other names, but MacArthur in particuar is consistent.

**Comment by tekd** [comment]
I think this is a csv mapping/slugging issue, not a db issue.
