### ISSUE TITLE
more prominent "submit" in footer

### ISSUE THREAD

**Issue by chrswng** [GovLab/open-government-research-exchange#60]
andrew wanted something like a submit button in the footer with the short description copy

**Comment by chrswng** [comment]
probably should say " SUBMIT RESEARCH"

**Comment by juliachrusciel** [comment]
I submitted a pull request for this issue.

**Comment by claudioccm** [comment]
I left a comment in the PR

**Comment by juliachrusciel** [comment]
in footer now
